### ISSUE TITLE
Disappearing platforms don't disappear if you keep jumping on them

### ISSUE THREAD

**Issue by FolkertVanVerseveld** [ErikaRedmark/monkey-shines-java-port#85]
In the original version, the platforms slighty descend (until they disappear of course) if you keep jumping on them. This doesn't happen in spooked (didn't test the other world, but I suspect they behave the same).

**Comment by ErikaRedmark** [comment]
I just tested and on my end, if you jump on a platform twice, it descends by one step. I believe this is the same as it was in the original, but my windows version of the old game won't run anymore for some reason so I can't confirm. If you stay still and keep jumping the collapsible platform it will eventually be destroyed.

**Comment by JeremyAvalon** [comment]
Just tested and got identical results to Erika, which is the correct behavior. (I've got the 1.2 Mac version lying around to compare with.)

**Comment by ErikaRedmark** [comment]
Finally closing issue given the feedback.
