### ISSUE TITLE
Momentum gets reset if you die

### ISSUE THREAD

**Issue by FolkertVanVerseveld** [ErikaRedmark/monkey-shines-java-port#86]
If you die in room 3,0 in spooked (the room above room 3,-1 where a skull guards a red key) the momentum gets reset. This does not happen in the original version. If you navigate from room 3,-1 to 3,0 you are still jumping in the air. If you die by touching the skull in room 3,0 you will reset to the position where you entered the room, but you will fall down immediatly back to room 3,-1.

**Comment by ErikaRedmark** [comment]
I'll work on the conservation of momentum. I don't think this should be too difficult to fix.

**Comment by ErikaRedmark** [comment]
In an unrelated test in Phils Mac World, found the momentum was indeed being conserved now, so I may have fixed this earlier but forgot to mark it as such.

Fix is on feature/use-slick2d branch, but it won't merge to master and I won't make a new release until I finish the Slick2D conversion and at least restore all the functionality that was lost.
