### ISSUE TITLE
Can't get out of help menu

### ISSUE THREAD

**Issue by FolkertVanVerseveld** [ErikaRedmark/monkey-shines-java-port#89]
Going to the help menu bricks the game because you can't go back (tested on Xubuntu). I don't know if this happens on all supported operating systems. Pressing anything on the keyboard or pressing any mouse button does not help.

**Comment by FolkertVanVerseveld** [comment]
Hmmm weird. Just tried it another couple of times and know it works. This was tested in Oracle's JVM, in OpenJDK I didn't have any problems with getting out of the help menu. I just clicked the window close button and it worked perfectly.

**Comment by ErikaRedmark** [comment]
The help window is a basic Swing dialog with a picture. If it isn't closing something is very, very, very wrong with Java. Is this still an issue or should I close this?

**Comment by FolkertVanVerseveld** [comment]
I can't reproduce the problem so I guess it is not an issue. Maybe it was just my confusing that you can't press a key to close the window.
